#!/bin/bash

javac -cp .:lib/py4j.jar -d bin src/java/Gate.java
javac -cp . -d bin src/java/Main.java
javac -cp . -d bin src/java/OperationCounter.java
javac -cp . -d bin src/java/Sorts.java
javac -cp . -d bin src/java/Tests.java
