#!/bin/bash

javac -cp src/java:lib/py4j.jar -d bin/java src/java/asd2/Gate.java \
	src/java/asd2/Main.java \
	src/java/asd2/OperationCounter.java \
	src/java/asd2/Sorts.java \
	src/java/asd2/Tests.java
